newIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the issue template!
newPRWelcomeComment: >
  Thanks for opening this pull request! Your Awesome! 🤺
firstPRMergeComment: >
  Congrats on merging your first pull request! 🎉🎉🎉
